import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { RegisterProvider } from "@/app/state";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overflow-x-hidden ${inter.className}`}>
        <div className='w-full h-full flex flex-col'>
          <div className="w-full h-16 bg-[#003078]">
            <div
              className="w-full h-2"
              style={{
                backgroundImage: 'linear-gradient(to right, #ffffff 0%, #ffffff 33.3%, #003183 33.3%, #003183 66.6%, #d0190f 66.6%, #d0190f 100%)',
                backgroundSize: '150px 100%',
                backgroundRepeat: 'repeat'
              }}
            >
            </div>
            <div className="mx-6 p-3 flex items-start justify-between h-full text-white">
              <span>Informačný systém registrácie kultúrnych subjektov</span>
            </div>
          </div>
          <div className="w-full h-20 flex justify-between text-2xl font-bold items-center py-12 px-6">
            <h3>Úprava registrov</h3>
            <div className="flex items-center">
              <svg className="cursor-pointer" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <mask id="mask0_23522_1158" maskUnits="userSpaceOnUse" x="0" y="0" width="24" height="24">
                  <circle cx="12" cy="11.9998" r="11.2" fill="#C4C4C4" />
                </mask>
                <g mask="url(#mask0_23522_1158)">
                  <rect x="4.80005" y="15.1997" width="14.4" height="12" rx="6" fill="#0065B3" />
                </g>
                <circle cx="12" cy="11.9998" r="10.2" stroke="#0065B3" strokeWidth="2" />
                <circle cx="12" cy="10.3999" r="4" fill="#0065B3" />
              </svg>
              <div className="flex flex-col pl-3">
                <p className="text-sm">Ing. Jožko Veľký M.A</p>
                <span className="text-sm font-normal underline cursor-pointer">Odhlásiť</span>
              </div>
            </div>
          </div>
        </div>

        <div className="p-6">
          <RegisterProvider>
            {children}
          </RegisterProvider>
        </div>
      </body>
    </html >
  );
}
